apiVersion: v1
kind: Secret
metadata:
  name: httpbin-secret
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFqeE52TWl1LzN3T1NuTGhObE9haworRThGTmhsTEY3N0xQc3R4S0l6UXRLMEQ4QUZWYWVQaUE5OTYvVnEvQzdyTHg0TXFwajd1NFRRTmUxRkFyMUZWCnE1V0xjMGtwTVQ2ZzZXa2JSZXZKV24vWVQ3YWM4YkFCSENkMlkwQzRQTlNXRmI0S0hUN2lyQUVQNDlyTkcvV0gKZWp2LzROalNObzVlVDd2ZUNyM3FPYm5uVW13aG5SallKdEd0T0RmWG9Bb29lQXJwckxVMUl3S1ZiK2V1clRWQwpDMUd5RUZPbVlwTm5aOXdFZjF1amhJSk8vTmZFQW4yR3RXSlZWY3VHZDhHZmxMbkNuZEhPOXhjdDVGdHpJU1hFClBHTUxsNmFCL1E5OS9GQVF5SGtzdTJIZVNmWnptVjJxdlFQWGtkQm9qb2R3M0F5KzlYVHhKRi9OS2dhTGdxUngKSVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg== # Use tls.crt field for the public key.
  tls.key: ""